apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tora-twitter-interactions-user-database
  namespace: $KUBE_NAMESPACE
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-client"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
---
apiVersion: v1
kind: Service
metadata:
  name: tora-twitter-interactions
  namespace: $KUBE_NAMESPACE
spec:
  type: ClusterIP
  selector:
    app: tora-twitter-interactions
  ports:
    - port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: tora-twitter-interactions
  name: tora-twitter-interactions
  namespace: $KUBE_NAMESPACE
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tora-twitter-interactions
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tora-twitter-interactions
    spec:
      containers:
      - image: $DOCKER_IMAGE_TAG
        imagePullPolicy: Always
        name: tora-twitter-interactions
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "8Gi"
            cpu: "1"
          limits:
            memory: "8Gi"
            cpu: "1"
        env:
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: dmi-secrets
              key: RABBITMQ_USER
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dmi-secrets
              key: RABBITMQ_PASSWORD
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: dmi-common-configs
              key: RABBITMQ_HOST
        - name: ENABLE_CHROME_DRIVER
          value: 'true'
        volumeMounts:
        - name: tora-twitter-interactions-user-database
          mountPath: /app/database
      volumes:
      - name: tora-twitter-interactions-user-database
        persistentVolumeClaim:
          claimName: tora-twitter-interactions-user-database
      imagePullSecrets:
        - name: registry-cred
status: {}
